//! Neovim.
//!
//! Two pieces, for the same reason as everywhere else. A generated Lua file
//! holds the theme, and `init.lua` gains one managed line that runs it.
//!
//! Placement is the whole trick here. The line goes at the *end* of `init.lua`,
//! after `require("config.lazy")`, because lazy.nvim loads plugins
//! synchronously during that call and LazyVim sets its own colourscheme while
//! it does. Running before it would be overwritten a moment later; running
//! after it wins.
//!
//! Live application works through Neovim's own socket. Since 0.10 every
//! instance listens on one under `$TMPDIR/nvim.$USER/`, so open editors can be
//! recoloured without restarting them.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::Result;

use crate::edit::{self, Placement};
use crate::which;
use crate::theme::Theme;

use super::{Detection, Outcome, Target, NVIM};

const BLOCK: &str = "nvim";

pub struct Neovim;

pub fn config_dir() -> PathBuf {
    if let Ok(xdg) = std::env::var("XDG_CONFIG_HOME") {
        if !xdg.is_empty() {
            return PathBuf::from(xdg).join("nvim");
        }
    }
    dirs::home_dir().unwrap_or_default().join(".config/nvim")
}

pub fn init_path() -> PathBuf {
    config_dir().join("init.lua")
}

pub fn generated_path() -> PathBuf {
    config_dir().join("lua/termdeck.lua")
}

/// Where lazy.nvim keeps the plugins it has installed.
fn lazy_dir() -> PathBuf {
    if let Ok(xdg) = std::env::var("XDG_DATA_HOME") {
        if !xdg.is_empty() {
            return PathBuf::from(xdg).join("nvim/lazy");
        }
    }
    dirs::home_dir()
        .unwrap_or_default()
        .join(".local/share/nvim/lazy")
}

/// The colourscheme plugins present on this machine.
///
/// Read from the plugin directory rather than by asking Neovim, because asking
/// means starting an editor and waiting for it, and this runs on every refresh
/// of the window.
pub fn installed_plugins() -> Vec<String> {
    let Ok(entries) = fs::read_dir(lazy_dir()) else {
        return Vec::new();
    };
    let mut names: Vec<String> = entries
        .filter_map(|entry| entry.ok())
        .filter(|entry| entry.path().is_dir())
        .filter_map(|entry| entry.file_name().to_str().map(|name| name.to_string()))
        .collect();
    names.sort();
    names
}

/// Which colourscheme this theme should use, and whether it is the one the
/// theme actually wanted.
///
/// A theme names a colourscheme and the plugin that provides it. When that
/// plugin is not installed, this falls back to the nearest catppuccin flavour
/// rather than asking for a colourscheme that does not exist — Neovim would
/// throw an error on startup and leave the editor on its default colours.
pub fn resolve(theme: &Theme, installed: &[String]) -> (String, bool) {
    let wanted = &theme.nvim;
    let have = installed.iter().any(|name| name == &wanted.plugin_name);

    if have {
        (wanted.colorscheme.clone(), true)
    } else {
        (
            format!("catppuccin-{}", theme.nearest_catppuccin_flavour()),
            false,
        )
    }
}

/// The generated Lua file.
pub fn theme_file(theme: &Theme, colorscheme: &str) -> String {
    let background = theme.mode.as_str();

    format!(
        "\
-- Generated by TermDeck. Every apply overwrites this file, so change the theme
-- in the app rather than editing here.
--
-- theme: {id}
-- mode:  {background}

vim.g.termdeck_theme = '{id}'

-- Background first, then the colourscheme. Several colourschemes read
-- 'background' when they load, so setting it afterwards would either do nothing
-- or quietly flip the variant back.
vim.o.background = '{background}'

-- Never let a missing colourscheme break startup: an uncaught error here would
-- leave the editor on its defaults with a message at every launch.
if not pcall(vim.cmd.colorscheme, '{colorscheme}') then
  pcall(vim.cmd.colorscheme, 'catppuccin')
end
",
        id = theme.id,
        background = background,
        colorscheme = colorscheme,
    )
}

/// The one line `init.lua` gains.
fn source_line() -> String {
    "pcall(dofile, vim.fn.stdpath('config') .. '/lua/termdeck.lua')".to_string()
}

/// Adds the managed line to `init.lua`.
pub fn rewrite_init(existing: &str) -> String {
    edit::upsert_block(existing, BLOCK, &source_line(), &Placement::End, edit::LUA)
}

/// Reads the theme id back out of a generated file.
pub fn current_theme(generated: &str) -> Option<String> {
    let line = generated
        .lines()
        .find(|line| line.starts_with("vim.g.termdeck_theme"))?;
    let id = line.split('\'').nth(1)?;
    Some(id.to_string())
}

/// The sockets of every Neovim currently running for this user.
///
/// Neovim creates one per instance under `$TMPDIR/nvim.$USER/<random>/`, which
/// is what makes recolouring an open editor possible at all.
pub fn running_sockets() -> Vec<PathBuf> {
    let base = std::env::temp_dir().join(format!(
        "nvim.{}",
        std::env::var("USER").unwrap_or_default()
    ));

    let mut sockets = Vec::new();
    let Ok(entries) = fs::read_dir(&base) else {
        return sockets;
    };

    for entry in entries.filter_map(|entry| entry.ok()) {
        let Ok(inner) = fs::read_dir(entry.path()) else {
            continue;
        };
        for socket in inner.filter_map(|socket| socket.ok()) {
            let path = socket.path();
            if is_socket(&path) {
                sockets.push(path);
            }
        }
    }

    sockets.sort();
    sockets
}

fn is_socket(path: &Path) -> bool {
    #[cfg(unix)]
    {
        use std::os::unix::fs::FileTypeExt;
        fs::metadata(path)
            .map(|meta| meta.file_type().is_socket())
            .unwrap_or(false)
    }
    #[cfg(not(unix))]
    {
        let _ = path;
        false
    }
}

/// The Lua sent to a running instance to recolour it.
pub fn live_lua(theme: &Theme, colorscheme: &str) -> String {
    format!(
        "luaeval(\"(function() vim.o.background='{}' pcall(vim.cmd.colorscheme,'{}') return 1 end)()\")",
        theme.mode.as_str(),
        colorscheme
    )
}

fn nvim_installed() -> bool {
    which::exists("nvim")
}

impl Target for Neovim {
    fn id(&self) -> &'static str {
        NVIM
    }

    fn name(&self) -> &'static str {
        "Neovim"
    }

    fn detect(&self) -> Detection {
        let init = init_path();
        let generated = generated_path();
        let installed = nvim_installed();
        let plugins = installed_plugins();
        let generated_text = edit::read_or_empty(&generated).unwrap_or_default();

        let schemes: Vec<&str> = plugins
            .iter()
            .map(|name| name.as_str())
            .filter(|name| {
                crate::theme::built_in_themes()
                    .iter()
                    .any(|theme| &theme.nvim.plugin_name == name)
            })
            .collect();

        let detail = if !installed {
            "Neovim is not installed".to_string()
        } else if !init.exists() {
            "no init.lua found".to_string()
        } else {
            let running = running_sockets().len();
            let base = if schemes.is_empty() {
                "no matching colourscheme plugins found; themes fall back to catppuccin".to_string()
            } else {
                format!("colourschemes available: {}", schemes.join(", "))
            };
            match running {
                0 => base,
                1 => format!("{base} · 1 editor open, so it recolours now"),
                n => format!("{base} · {n} editors open, so they recolour now"),
            }
        };

        Detection {
            id: NVIM.to_string(),
            name: "Neovim".to_string(),
            installed: installed && init.exists(),
            paths: vec![
                super::display_path(&init),
                super::display_path(&generated),
            ],
            detail,
            current_theme: current_theme(&generated_text),
        }
    }

    fn apply(&self, theme: &Theme, options: &super::ApplyOptions) -> Result<Outcome> {
        if !nvim_installed() {
            return Ok(Outcome::skipped(NVIM, "Neovim", "Neovim is not installed"));
        }

        let init = init_path();
        if !init.exists() {
            return Ok(Outcome::skipped(
                NVIM,
                "Neovim",
                "no init.lua to hook into",
            ));
        }

        let installed = installed_plugins();
        let (colorscheme, exact) = resolve(theme, &installed);

        let mut changed = Vec::new();

        let generated = generated_path();
        let wanted = theme_file(theme, &colorscheme);
        if edit::read_or_empty(&generated)? != wanted {
            edit::write_with_backup(&generated, &wanted)?;
        }
        changed.push(generated);

        let existing = edit::read_or_empty(&init)?;
        let updated = rewrite_init(&existing);
        if updated != existing {
            edit::write_with_backup(&init, &updated)?;
            changed.push(init);
        }

        // Say plainly when the theme is an approximation rather than the thing
        // asked for, since the editor will visibly not match the terminal.
        let substitution = if exact {
            String::new()
        } else {
            format!(
                " {} is not installed, so Neovim uses {colorscheme} instead.",
                theme.nvim.plugin
            )
        };

        let sockets = if options.live {
            running_sockets()
        } else {
            Vec::new()
        };

        if sockets.is_empty() {
            return Ok(Outcome::pending(
                NVIM,
                "Neovim",
                format!("Set to {colorscheme}.{substitution}"),
                changed,
                "Applies the next time you open Neovim.",
            ));
        }

        let expression = live_lua(theme, &colorscheme);
        let mut recoloured = 0;
        let mut failures = Vec::new();

        for socket in &sockets {
            let Some(mut nvim) = which::command("nvim") else {
                break;
            };
            let out = nvim
                .arg("--server")
                .arg(socket)
                .arg("--remote-expr")
                .arg(&expression)
                .output();

            match out {
                Ok(out) if out.status.success() => recoloured += 1,
                Ok(out) => failures.push(String::from_utf8_lossy(&out.stderr).trim().to_string()),
                Err(error) => failures.push(error.to_string()),
            }
        }

        if recoloured == 0 {
            return Ok(Outcome::pending(
                NVIM,
                "Neovim",
                format!(
                    "Set to {colorscheme}, but no open editor took it: {}",
                    failures.join("; ")
                ),
                changed,
                "Applies the next time you open Neovim.",
            ));
        }

        let editors = if recoloured == 1 {
            "1 open editor".to_string()
        } else {
            format!("{recoloured} open editors")
        };

        Ok(Outcome::applied(
            NVIM,
            "Neovim",
            format!("Recoloured {editors} to {colorscheme}.{substitution}"),
            changed,
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theme::{find, Mode};

    /// The real `init.lua` from a LazyVim setup is exactly this short.
    const INIT: &str = "\
-- bootstrap lazy.nvim, LazyVim and your plugins
require(\"config.lazy\")
";

    fn installed(names: &[&str]) -> Vec<String> {
        names.iter().map(|name| name.to_string()).collect()
    }

    #[test]
    fn the_managed_line_runs_after_lazy_loads() {
        // LazyVim sets its own colourscheme while lazy.nvim loads. Ours has to
        // come after that call or it is simply overwritten.
        let out = rewrite_init(INIT);
        let lazy = out.find("require(\"config.lazy\")").unwrap();
        let ours = out.find("termdeck.lua").unwrap();
        assert!(ours > lazy, "our line must come after lazy loads");
    }

    #[test]
    fn init_lua_is_commented_as_lua() {
        // A `#` here is a syntax error and Neovim would fail to start.
        let out = rewrite_init(INIT);
        assert!(out.contains("-- >>> termdeck:nvim >>>"));
        assert!(!out.contains("# >>>"));
    }

    #[test]
    fn the_users_init_survives() {
        let out = rewrite_init(INIT);
        assert!(out.contains("require(\"config.lazy\")"));
        assert!(out.contains("-- bootstrap lazy.nvim"));
    }

    #[test]
    fn wiring_init_twice_adds_one_line() {
        let once = rewrite_init(INIT);
        let twice = rewrite_init(&once);
        assert_eq!(once, twice);
        assert_eq!(twice.matches("termdeck.lua").count(), 1);
    }

    #[test]
    fn an_installed_colourscheme_is_used_directly() {
        let tokyo = find("tokyo-night").unwrap();
        let (scheme, exact) = resolve(&tokyo, &installed(&["tokyonight.nvim", "catppuccin"]));
        assert_eq!(scheme, "tokyonight-night");
        assert!(exact);
    }

    #[test]
    fn catppuccin_flavours_resolve_to_their_own_scheme() {
        for (id, scheme) in [
            ("catppuccin-latte", "catppuccin-latte"),
            ("catppuccin-frappe", "catppuccin-frappe"),
            ("catppuccin-macchiato", "catppuccin-macchiato"),
            ("catppuccin-mocha", "catppuccin-mocha"),
        ] {
            let theme = find(id).unwrap();
            let (got, exact) = resolve(&theme, &installed(&["catppuccin"]));
            assert_eq!(got, scheme);
            assert!(exact);
        }
    }

    #[test]
    fn a_missing_plugin_falls_back_to_a_same_mode_catppuccin() {
        // Dracula's plugin is not installed here, so Neovim must not be told to
        // load a colourscheme that does not exist.
        let dracula = find("dracula").unwrap();
        let (scheme, exact) = resolve(&dracula, &installed(&["catppuccin"]));
        assert_eq!(scheme, "catppuccin-mocha", "a dark theme needs a dark fallback");
        assert!(!exact, "the substitution has to be reported");

        let dawn = find("rose-pine-dawn").unwrap();
        let (scheme, exact) = resolve(&dawn, &installed(&["catppuccin"]));
        assert_eq!(scheme, "catppuccin-latte", "a light theme needs a light fallback");
        assert!(!exact);
    }

    #[test]
    fn nothing_installed_still_produces_a_usable_colourscheme() {
        for theme in crate::theme::built_in_themes() {
            let (scheme, exact) = resolve(&theme, &[]);
            assert!(!exact);
            assert!(
                scheme.starts_with("catppuccin-"),
                "{} fell back to {scheme}",
                theme.id
            );
        }
    }

    #[test]
    fn background_is_set_before_the_colourscheme() {
        // Several colourschemes read 'background' as they load.
        let text = theme_file(&find("catppuccin-mocha").unwrap(), "catppuccin-mocha");
        let background = text.find("vim.o.background").unwrap();
        let scheme = text.find("vim.cmd.colorscheme").unwrap();
        assert!(background < scheme);
    }

    #[test]
    fn the_generated_file_never_breaks_startup() {
        // Every call that could fail is wrapped, and there is a fallback.
        let text = theme_file(&find("dracula").unwrap(), "dracula");
        assert!(text.contains("pcall(vim.cmd.colorscheme, 'dracula')"));
        assert!(text.contains("pcall(vim.cmd.colorscheme, 'catppuccin')"));
    }

    #[test]
    fn the_generated_file_records_its_theme() {
        let text = theme_file(&find("nord").unwrap(), "nord");
        assert_eq!(current_theme(&text).as_deref(), Some("nord"));
    }

    #[test]
    fn light_and_dark_set_the_matching_background() {
        let light = theme_file(&find("catppuccin-latte").unwrap(), "catppuccin-latte");
        assert!(light.contains("vim.o.background = 'light'"));

        let dark = theme_file(&find("catppuccin-mocha").unwrap(), "catppuccin-mocha");
        assert!(dark.contains("vim.o.background = 'dark'"));
    }

    #[test]
    fn the_source_line_tolerates_a_missing_generated_file() {
        // Deleting the generated file must not stop Neovim from starting.
        let out = rewrite_init(INIT);
        assert!(out.contains("pcall(dofile"));
    }

    #[test]
    fn the_generated_file_is_run_not_required() {
        // `require` caches, so a second apply in the same session would be a
        // no-op. `dofile` re-reads every time.
        let out = rewrite_init(INIT);
        assert!(out.contains("dofile"));
        assert!(!out.contains("require('termdeck')"));
    }

    #[test]
    fn the_live_expression_sets_both_background_and_scheme() {
        let lua = live_lua(&find("catppuccin-mocha").unwrap(), "catppuccin-mocha");
        assert!(lua.contains("background='dark'"));
        assert!(lua.contains("catppuccin-mocha"));
        // Sent through --remote-expr, so it has to be one expression.
        assert!(lua.starts_with("luaeval("));
    }

    #[test]
    fn the_live_expression_cannot_error_out_a_running_editor() {
        let lua = live_lua(&find("dracula").unwrap(), "dracula");
        assert!(lua.contains("pcall"));
    }

    #[test]
    fn every_theme_names_a_plugin_and_a_scheme() {
        for theme in crate::theme::built_in_themes() {
            assert!(!theme.nvim.colorscheme.is_empty(), "{}", theme.id);
            assert!(!theme.nvim.plugin.is_empty(), "{}", theme.id);
            assert!(!theme.nvim.plugin_name.is_empty(), "{}", theme.id);
            assert!(
                theme.nvim.plugin.contains('/'),
                "{} should name a repository",
                theme.id
            );
        }
    }

    #[test]
    fn no_theme_reported_for_an_ungenerated_file() {
        assert_eq!(current_theme(""), None);
        assert_eq!(current_theme("vim.o.background = 'dark'\n"), None);
    }

    #[test]
    fn a_light_theme_never_falls_back_to_a_dark_editor() {
        // Getting this backwards would be the most visible possible bug.
        for theme in crate::theme::built_in_themes() {
            let (scheme, _) = resolve(&theme, &[]);
            let dark_fallback = scheme.contains("mocha")
                || scheme.contains("frappe")
                || scheme.contains("macchiato");
            match theme.mode {
                Mode::Light => assert!(!dark_fallback, "{} fell back to {scheme}", theme.id),
                Mode::Dark => assert!(dark_fallback, "{} fell back to {scheme}", theme.id),
            }
        }
    }
}
