//! zsh, meaning the powerlevel10k prompt and the fzf colours.
//!
//! The palette lives in a generated file and `.zshrc` only gains one line that
//! sources it. That keeps a 200-line hand-written dotfile from filling up with
//! colour assignments every time the theme changes.
//!
//! Placement matters here too. The block goes at the end of `.zshrc`, after the
//! line that sources `~/.p10k.zsh`, because the last assignment to a
//! `POWERLEVEL9K_*` variable is the one the prompt uses.

use std::path::PathBuf;

use anyhow::Result;

use crate::edit::{self, Placement};
use crate::theme::Theme;

use super::{Detection, Outcome, Target, ZSH};

const BLOCK: &str = "zsh";

pub struct Zsh;

pub fn zshrc_path() -> PathBuf {
    dirs::home_dir().unwrap_or_default().join(".zshrc")
}

pub fn theme_file_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".config/termdeck/zsh-theme.zsh")
}

/// The single line `.zshrc` gains.
fn source_line() -> String {
    "[[ -f ~/.config/termdeck/zsh-theme.zsh ]] && source ~/.config/termdeck/zsh-theme.zsh"
        .to_string()
}

/// Builds the generated theme file.
///
/// powerlevel10k takes colours as 256-palette indices rather than hex, so each
/// prompt colour is mapped to its nearest index on the way out. fzf does
/// understand truecolor hex, so it gets the exact values.
pub fn theme_file(theme: &Theme) -> String {
    let p = &theme.palette;
    let index = |color: &crate::color::Rgb| color.to_xterm256().to_string();

    let fzf = [
        format!("bg+:{}", p.surface.hex()),
        format!("bg:{}", p.background.hex()),
        format!("spinner:{}", p.accent.hex()),
        format!("hl:{}", p.ansi.red.hex()),
        format!("fg:{}", p.foreground.hex()),
        format!("header:{}", p.ansi.red.hex()),
        format!("info:{}", p.accent.hex()),
        format!("pointer:{}", p.accent.hex()),
        format!("marker:{}", p.ansi.green.hex()),
        format!("fg+:{}", p.foreground.hex()),
        format!("prompt:{}", p.accent.hex()),
        format!("hl+:{}", p.ansi.red.hex()),
        format!("border:{}", p.subtle.hex()),
        format!("gutter:{}", p.background.hex()),
    ]
    .join(",");

    format!(
        "\
# Generated by TermDeck. Every apply overwrites this file, so change the theme
# in the app rather than editing here.
#
# theme: {id}
# mode:  {mode}

export TERMDECK_THEME='{id}'
export TERMDECK_MODE='{mode}'

# fzf takes truecolor hex directly.
export FZF_DEFAULT_OPTS=\"--color={fzf}\"

# powerlevel10k only understands 256-colour indices, so these are the nearest
# palette entries to the theme's colours.
typeset -g POWERLEVEL9K_DIR_FOREGROUND={dir}
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND={dir_anchor}
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND={vcs_clean}
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND={vcs_modified}
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND={vcs_untracked}
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND={ok}
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND={ok}
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND={ok}
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND={error}
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND={error}
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND={error}
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND={ok}
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND={error}
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND={subtle}
typeset -g POWERLEVEL9K_TIME_FOREGROUND={subtle}
typeset -g POWERLEVEL9K_BACKGROUND=

# Redraw the prompt if powerlevel10k is already loaded, so `source`-ing this
# file in an open shell is enough to see the change.
(( $+functions[p10k] )) && p10k reload
",
        id = theme.id,
        mode = theme.mode.as_str(),
        fzf = fzf,
        dir = index(&p.accent),
        dir_anchor = index(&p.ansi.blue),
        vcs_clean = index(&p.ansi.green),
        vcs_modified = index(&p.ansi.yellow),
        vcs_untracked = index(&p.ansi.red),
        ok = index(&p.ansi.green),
        error = index(&p.ansi.red),
        subtle = index(&p.subtle),
    )
}

/// Adds the source line to `.zshrc` if it is not already there.
pub fn rewrite_zshrc(existing: &str) -> String {
    edit::upsert_block(existing, BLOCK, &source_line(), &Placement::End, edit::HASH)
}

/// Reads the theme id back out of a generated theme file.
pub fn current_theme(theme_file_text: &str) -> Option<String> {
    let line = theme_file_text
        .lines()
        .find(|line| line.starts_with("export TERMDECK_THEME="))?;
    let id = line.split('\'').nth(1)?;
    Some(id.to_string())
}

impl Target for Zsh {
    fn id(&self) -> &'static str {
        ZSH
    }

    fn name(&self) -> &'static str {
        "zsh + powerlevel10k"
    }

    fn detect(&self) -> Detection {
        let zshrc = zshrc_path();
        let generated = theme_file_path();
        let existing = edit::read_or_empty(&zshrc).unwrap_or_default();
        let generated_text = edit::read_or_empty(&generated).unwrap_or_default();

        let has_p10k = existing.contains("powerlevel10k") || existing.contains("p10k");
        let wired = edit::read_block(&existing, BLOCK).is_some();

        let detail = if !zshrc.exists() {
            "no ~/.zshrc found".to_string()
        } else if !has_p10k {
            "no powerlevel10k found; fzf colours will still be set".to_string()
        } else if wired {
            "wired up; prompt and fzf follow the theme".to_string()
        } else {
            "powerlevel10k found — TermDeck will add one source line".to_string()
        };

        Detection {
            id: ZSH.to_string(),
            name: "zsh + powerlevel10k".to_string(),
            installed: zshrc.exists(),
            paths: vec![
                super::display_path(&zshrc),
                super::display_path(&generated),
            ],
            detail,
            current_theme: current_theme(&generated_text),
        }
    }

    fn apply(&self, theme: &Theme, _options: &super::ApplyOptions) -> Result<Outcome> {
        let zshrc = zshrc_path();
        if !zshrc.exists() {
            return Ok(Outcome::skipped(ZSH, "zsh + powerlevel10k", "no ~/.zshrc"));
        }

        let mut changed = Vec::new();

        let generated = theme_file_path();
        let wanted = theme_file(theme);
        if edit::read_or_empty(&generated)? != wanted {
            edit::write_with_backup(&generated, &wanted)?;
        }
        changed.push(generated);

        let existing = edit::read_or_empty(&zshrc)?;
        let updated = rewrite_zshrc(&existing);
        if updated != existing {
            edit::write_with_backup(&zshrc, &updated)?;
            changed.push(zshrc);
        }

        // A running shell cannot be reached from outside its own process, so
        // this is honestly pending rather than applied.
        Ok(Outcome::pending(
            ZSH,
            "zsh + powerlevel10k",
            format!("Prompt and fzf colours set to {}.", theme.name),
            changed,
            "Run `source ~/.config/termdeck/zsh-theme.zsh` in any open shell, or just open a new one.",
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theme::find;

    #[test]
    fn the_generated_file_records_its_theme() {
        let mocha = find("catppuccin-mocha").unwrap();
        let text = theme_file(&mocha);
        assert!(text.contains("export TERMDECK_THEME='catppuccin-mocha'"));
        assert!(text.contains("export TERMDECK_MODE='dark'"));
        assert_eq!(current_theme(&text).as_deref(), Some("catppuccin-mocha"));
    }

    #[test]
    fn fzf_gets_truecolor_hex() {
        let latte = find("catppuccin-latte").unwrap();
        let text = theme_file(&latte);
        assert!(text.contains("FZF_DEFAULT_OPTS"));
        assert!(text.contains("bg:#eff1f5"), "should use latte's background");
        assert!(text.contains("prompt:#8839ef"), "should use latte's accent");
    }

    #[test]
    fn p10k_gets_palette_indices_not_hex() {
        // powerlevel10k rejects hex, so a `#` anywhere in these assignments
        // would silently break the prompt.
        let latte = find("catppuccin-latte").unwrap();
        for line in theme_file(&latte)
            .lines()
            .filter(|line| line.contains("POWERLEVEL9K"))
        {
            assert!(!line.contains('#'), "p10k cannot read hex: {line}");
        }
    }

    #[test]
    fn every_p10k_colour_is_a_valid_index() {
        for theme in crate::theme::built_in_themes() {
            for line in theme_file(&theme)
                .lines()
                .filter(|line| line.contains("_FOREGROUND="))
            {
                let value = line.split('=').nth(1).unwrap().trim();
                if value.is_empty() {
                    continue;
                }
                let index: u16 = value
                    .parse()
                    .unwrap_or_else(|_| panic!("{} produced `{line}`", theme.id));
                assert!(index <= 255, "{} produced index {index}", theme.id);
            }
        }
    }

    #[test]
    fn light_and_dark_themes_produce_different_prompts() {
        let latte = theme_file(&find("catppuccin-latte").unwrap());
        let mocha = theme_file(&find("catppuccin-mocha").unwrap());
        assert_ne!(latte, mocha);
    }

    #[test]
    fn zshrc_gains_exactly_one_line() {
        let existing = "ZSH_THEME=\"powerlevel10k/powerlevel10k\"\nsource ~/.p10k.zsh\n";
        let out = rewrite_zshrc(existing);
        assert_eq!(out.matches("source ~/.config/termdeck/zsh-theme.zsh").count(), 1);
        assert!(out.contains("ZSH_THEME=\"powerlevel10k/powerlevel10k\""));
    }

    #[test]
    fn the_block_lands_after_p10k_is_sourced() {
        // p10k config assigns these same variables; ours must be assigned last.
        let existing = "ZSH_THEME=\"powerlevel10k/powerlevel10k\"\n[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh\n";
        let out = rewrite_zshrc(existing);
        let p10k = out.find("source ~/.p10k.zsh").unwrap();
        let ours = out.find("termdeck/zsh-theme.zsh").unwrap();
        assert!(ours > p10k, "our colours have to be assigned last");
    }

    #[test]
    fn wiring_zshrc_twice_changes_nothing_the_second_time() {
        let existing = "source ~/.p10k.zsh\n";
        let once = rewrite_zshrc(existing);
        let twice = rewrite_zshrc(&once);
        assert_eq!(once, twice);
        assert_eq!(twice.matches("# >>> termdeck:zsh >>>").count(), 1);
    }

    #[test]
    fn the_source_line_tolerates_a_missing_file() {
        // If the generated file is deleted, the shell must still start.
        let out = rewrite_zshrc("");
        assert!(out.contains("[[ -f ~/.config/termdeck/zsh-theme.zsh ]] &&"));
    }

    #[test]
    fn an_open_shell_can_pick_the_theme_up_by_sourcing_it() {
        let text = theme_file(&find("dracula").unwrap());
        assert!(text.contains("p10k reload"));
    }

    #[test]
    fn no_theme_reported_for_an_ungenerated_file() {
        assert_eq!(current_theme(""), None);
        assert_eq!(current_theme("export SOMETHING='x'\n"), None);
    }
}
